const S={cards:[],filtered:[],page:1,perPage:60,q:'',set:'',f:{rookie:false,autograph:false,memorabilia:false,serial:false},sort:'relevance'};
const app=document.getElementById('app');
const fmt=new Intl.NumberFormat();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
function cardNumber(c){return clean(c.number||c.cardNumber||c.normalizedNumber).replace(/^#/,'')}
function canonicalName(c,opts={hash:true}){const n=cardNumber(c);const num=n?(opts.hash?`#${n}`:n):'';return [clean(c.year),clean(c.set),clean(c.player||c.title),num].filter(Boolean).join(' ').replace(/\s+/g,' ').trim()}
function sportsCardsProDirect(c){return c.sportsCardsProUrl||c.sportscardsproUrl||c.priceChartingUrl||c.marketplaceUrls?.sportsCardsPro||c.marketplaceUrls?.sportscardspro||''}
function queries(c){const exact=canonicalName(c,{hash:true})||clean(c.searchQuery)||clean(c.title);const noHash=canonicalName(c,{hash:false})||exact.replace(/#/g,'');const mq=c.marketplaceQueries||{};return{ebayActiveRaw:`${exact} raw`,ebaySold:mq.ebaySold||exact,google:exact,one30point:noHash,sportsCardsPro:exact}}
function sportsCardsProUrl(c){const direct=sportsCardsProDirect(c);if(direct)return direct;if(String(c.id)==='26391567'||canonicalName(c,{hash:true})==='2023 Topps X Bob Ross The Joy of Baseball Shohei Ohtani #1')return 'https://www.sportscardspro.com/game/baseball-cards-2023-topps-x-bob-ross-the-joy-of/shohei-ohtani-1';return `https://www.sportscardspro.com/search-products?q=${encodeURIComponent(canonicalName(c,{hash:true}))}&type=prices`}
function marketUrl(k,q,c){const e=encodeURIComponent(q||'');if(k==='ebayActiveRaw')return`https://www.ebay.com/sch/i.html?_nkw=${e}&_sacat=212&LH_PrefLoc=2`;if(k==='ebaySold')return`https://www.ebay.com/sch/i.html?_nkw=${e}&_sacat=212&LH_Sold=1&LH_Complete=1`;if(k==='google')return`https://www.google.com/search?q=${e}`;if(k==='sportsCardsPro')return sportsCardsProUrl(c);return'#'}
function idFromPath(){const m=location.pathname.match(/\/cards\/([^/?#]+?)(?:\.html)?\/?$/i);return m?decodeURIComponent(m[1]):null}
function url(c){return`/cards/${encodeURIComponent(c.id)}.html`}
function qrTarget(c){return c.url||`https://cards.allcardcomps.com/cards/${c.id}.html`}
function qrImg(c){return`https://quickchart.io/qr?text=${encodeURIComponent(qrTarget(c))}&size=220&margin=1&ecLevel=Q`}
function searchText(c){const q=queries(c);return[c.id,c.title,c.player,c.year,c.set,c.number,c.normalizedNumber,c.searchQuery,c.team,c.parallel,c.conditionFocus,q.ebayActiveRaw,q.ebaySold,q.google,q.one30point,q.sportsCardsPro].join(' ').toLowerCase()}
function nav(){return`<div class="topbar wrap"><div class="brand"><div class="logo">ACC</div><div>All Card Comps</div></div><a href="/" data-link>Search</a></div>`}
function toast(m){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent=m;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),1500)}
async function copyText(x){try{await navigator.clipboard.writeText(x);toast('Copied')}catch{toast('Copy failed')}}
function open130Point(query){copyText(query);window.open('https://130point.com/search','_blank','noopener')}
function price(c){const a=c.estimatedLowMarketPriceDisplay,b=c.estimatedHighMarketPriceDisplay;return a&&b?`<div class="price"><strong>Est. raw market</strong><br>${esc(a)} – ${esc(b)}</div>`:''}
function badges(c){const b=[];if(c.rookie)b.push('RC');if(c.autograph)b.push('Auto');if(c.memorabilia)b.push('Relic');if(c.serial||(c.printRun&&c.printRun!=='0'))b.push(c.printRun&&c.printRun!=='0'?`/${c.printRun}`:'Serial');if(!b.length)b.push(c.parallel||'Base');return`<div class="badges">${b.map(x=>`<span class="badge">${esc(x)}</span>`).join('')}</div>`}
function apply(){const term=S.q.trim().toLowerCase();S.filtered=S.cards.filter(c=>(!S.set||c.set===S.set)&&(!S.f.rookie||c.rookie)&&(!S.f.autograph||c.autograph)&&(!S.f.memorabilia||c.memorabilia)&&(!S.f.serial||c.serial||(c.printRun&&c.printRun!=='0'))&&(!term||searchText(c).includes(term)));if(S.sort==='yearDesc')S.filtered.sort((a,b)=>(+b.year||0)-(+a.year||0));if(S.sort==='priceDesc')S.filtered.sort((a,b)=>(+b.estimatedHighMarketPrice||0)-(+a.estimatedHighMarketPrice||0))}
function cardTile(c){const q=queries(c);return`<article class="card"><div class="title">${esc(c.title||q.google)}</div><div class="sub">${esc(c.year)} · ${esc(c.set)} · ${esc(c.number||'')}</div>${price(c)}<div class="query"><strong>eBay raw:</strong><br>${esc(q.ebayActiveRaw)}</div><div class="query"><strong>130point query:</strong><br>${esc(q.one30point)}</div>${badges(c)}<div class="actions"><a class="btn primary" href="${url(c)}" data-link>Open</a><a class="btn outline" target="_blank" rel="noopener" href="${marketUrl('ebaySold',q.ebaySold,c)}">eBay sold</a><button class="btn orange" type="button" data-open130="${esc(q.one30point)}">Copy + open 130point</button><a class="btn outline" target="_blank" rel="noopener" href="${marketUrl('sportsCardsPro',q.sportsCardsPro,c)}">SportsCardsPro</a><button class="btn outline" type="button" data-copy="${esc(q.one30point)}">Copy</button></div></article>`}
function rows(){const matchCount=document.getElementById('matchCount'),resultMeta=document.getElementById('resultMeta'),pageInfo=document.getElementById('pageInfo'),prev=document.getElementById('prev'),next=document.getElementById('next'),resultsList=document.getElementById('resultsList');const pages=Math.max(1,Math.ceil(S.filtered.length/S.perPage));if(S.page>pages)S.page=pages;const start=(S.page-1)*S.perPage,rs=S.filtered.slice(start,start+S.perPage);matchCount.textContent=fmt.format(S.filtered.length);resultMeta.textContent=S.filtered.length?`Showing ${fmt.format(start+1)}–${fmt.format(start+rs.length)} of ${fmt.format(S.filtered.length)}`:'No matches';pageInfo.textContent=`Page ${S.page} of ${pages}`;prev.disabled=S.page<=1;next.disabled=S.page>=pages;resultsList.innerHTML=rs.length?rs.map(cardTile).join(''):'<div class="panel">No cards matched.</div>'}
function bindCommonClicks(root=document){root.onclick=e=>{const copy=e.target.closest('[data-copy]');if(copy)copyText(copy.getAttribute('data-copy'));const p=e.target.closest('[data-open130]');if(p)open130Point(p.getAttribute('data-open130'))}}
function home(){const sets=[...new Set(S.cards.map(c=>c.set).filter(Boolean))].sort(),stats={cards:S.cards.length,sets:sets.length,rookies:S.cards.filter(c=>c.rookie).length,serial:S.cards.filter(c=>c.serial||(c.printRun&&c.printRun!=='0')).length};app.innerHTML=`${nav()}<div class="wrap"><section class="hero"><h1>Search cards. Open comps. Copy stronger queries.</h1><p>Responsive card comp pages with 130point copy-and-open workflow, marketplace buttons, filters, pagination, and detail pages.</p></section><section class="panel stats"><div class="stat"><span>Cards</span><b>${fmt.format(stats.cards)}</b></div><div class="stat"><span>Sets</span><b>${fmt.format(stats.sets)}</b></div><div class="stat"><span>Rookies</span><b>${fmt.format(stats.rookies)}</b></div><div class="stat"><span>Serial/SP</span><b>${fmt.format(stats.serial)}</b></div></section><section class="panel searchShell"><div class="searchbar"><input id="searchInput" type="text" placeholder="Search cards, players, sets, numbers"><select id="setSel"><option value="">All sets</option>${sets.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('')}</select></div><div class="chips">${['rookie','autograph','memorabilia','serial'].map(k=>`<label class="chip"><input id="${k}" type="checkbox"> ${k}</label>`).join('')}<label class="chip">Sort:<select id="sortSel"><option value="relevance">relevance</option><option value="yearDesc">Newest year</option><option value="priceDesc">Highest est. price</option></select></label></div></section><section class="toolbar"><div><strong id="matchCount">0</strong> matches · <span id="resultMeta"></span></div><div class="pager"><button id="prev" class="btn outline" type="button">Previous</button><span id="pageInfo"></span><button id="next" class="btn outline" type="button">Next</button></div></section><section id="resultsList" class="results"></section><div class="foot">Verify live sold listings before pricing inventory.</div></div>`;document.getElementById('searchInput').oninput=e=>{S.q=e.target.value;S.page=1;apply();rows()};document.getElementById('setSel').onchange=e=>{S.set=e.target.value;S.page=1;apply();rows()};document.getElementById('sortSel').onchange=e=>{S.sort=e.target.value;S.page=1;apply();rows()};['rookie','autograph','memorabilia','serial'].forEach(k=>document.getElementById(k).onchange=e=>{S.f[k]=e.target.checked;S.page=1;apply();rows()});document.getElementById('prev').onclick=()=>{if(S.page>1){S.page--;rows()}};document.getElementById('next').onclick=()=>{const pages=Math.max(1,Math.ceil(S.filtered.length/S.perPage));if(S.page<pages){S.page++;rows()}};bindCommonClicks(document.getElementById('resultsList'));apply();rows()}
function detail(c){const q=queries(c);const items=[['eBay active raw',q.ebayActiveRaw,marketUrl('ebayActiveRaw',q.ebayActiveRaw,c),'link'],['eBay sold',q.ebaySold,marketUrl('ebaySold',q.ebaySold,c),'link'],['Google comps',q.google,marketUrl('google',q.google,c),'link'],['130point',q.one30point,'https://130point.com/search','open130'],['SportsCardsPro',q.sportsCardsPro,marketUrl('sportsCardsPro',q.sportsCardsPro,c),'link']];app.innerHTML=`${nav()}<div class="wrap"><a class="btn outline" href="/" data-link>← Back</a><section class="panel detail"><div><h2>${esc(c.title||q.google)}</h2><p>${esc(c.year)} · ${esc(c.set)} · ${esc(c.number||'')}${c.team?' · '+esc(c.team):''}</p>${badges(c)}<div class="metaGrid" style="margin-top:16px"><div class="meta">${price(c)||'<strong>Est. raw market</strong><br>n/a'}</div><div class="meta"><strong>Player</strong><br>${esc(c.player)}</div><div class="meta"><strong>Set</strong><br>${esc(c.set)}</div><div class="meta"><strong>Card #</strong><br>${esc(c.number||'')}</div><div class="meta"><strong>ID</strong><br>${esc(c.id)}</div><div class="meta"><strong>Canonical query</strong><br>${esc(q.google)}</div></div><h3 style="margin-top:18px">Marketplace searches</h3><div class="marketGrid">${items.map(([label,value,href,type])=>`<div class="market"><strong>${esc(label)}</strong><div class="query" style="margin-top:10px">${esc(value)}</div><div class="actions">${type==='open130'?`<button class="btn orange" type="button" data-open130="${esc(value)}">Copy + open 130point</button>`:`<a class="btn primary" target="_blank" rel="noopener" href="${href}">Open</a>`}<button class="btn outline" type="button" data-copy="${esc(value)}">Copy</button></div></div>`).join('')}</div></div><aside><div class="qr"><h3>QR label</h3><img src="${qrImg(c)}" alt="QR code"><p>Links to this card page.</p></div></aside></section></div>`;bindCommonClicks(document)}
function router(){const id=idFromPath();if(id){const c=S.cards.find(x=>String(x.id)===String(id));c?detail(c):home()}else home()}
document.addEventListener('click',e=>{const a=e.target.closest('a[data-link]');if(a){e.preventDefault();history.pushState(null,'',a.getAttribute('href'));router()}});addEventListener('popstate',router);fetch('/cards.json',{cache:'no-store'}).then(r=>r.json()).then(d=>{S.cards=d.cards||[];router()}).catch(e=>{app.innerHTML=`${nav()}<div class="wrap"><div class="panel"><h2>Could not load cards.json</h2><p>${esc(e.message)}</p></div></div>`});
