const S={cards:[],filtered:[],page:1,perPage:60,q:'',year:'',set:'',f:{rookie:false,autograph:false,memorabilia:false,serial:false}};
const app=document.getElementById('app');
const themes=['mint','gold','electric'];
function setTheme(theme){const next=themes.includes(theme)?theme:'mint';document.documentElement.dataset.theme=next;try{localStorage.setItem('cardTheme',next)}catch{};syncThemeButtons()}
function syncThemeButtons(){document.querySelectorAll('[data-theme-btn]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.themeBtn===(document.documentElement.dataset.theme||'mint')))}
try{setTheme(localStorage.getItem('cardTheme')||'mint')}catch{setTheme('mint')}
const fmt=new Intl.NumberFormat();
const collator=new Intl.Collator(undefined,{numeric:true,sensitivity:'base'});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
function cardNumber(c){return clean(c.number||c.cardNumber||c.normalizedNumber).replace(/^#/,'')}
function canonicalName(c,opts={hash:true}){const n=cardNumber(c);const num=n?(opts.hash?`#${n}`:n):'';return [clean(c.year),clean(c.set),clean(c.player||c.title),num].filter(Boolean).join(' ').replace(/\s+/g,' ').trim()}
function sportsCardsProDirect(c){return c.sportsCardsProUrl||c.sportscardsproUrl||c.priceChartingUrl||c.marketplaceUrls?.sportsCardsPro||c.marketplaceUrls?.sportscardspro||''}
function queries(c){const exact=canonicalName(c,{hash:true})||clean(c.searchQuery)||clean(c.title);const noHash=canonicalName(c,{hash:false})||exact.replace(/#/g,'');const mq=c.marketplaceQueries||{};return{ebayActiveRaw:mq.ebayActiveRaw||exact,ebaySold:mq.ebaySold||exact,google:mq.google||exact,one30point:mq.one30point||noHash,sportsCardsPro:mq.sportsCardsPro||exact}}
function sportsCardsProUrl(c){const direct=sportsCardsProDirect(c);if(direct)return direct;if(String(c.id)==='26391567'||canonicalName(c,{hash:true})==='2023 Topps X Bob Ross The Joy of Baseball Shohei Ohtani #1')return 'https://www.sportscardspro.com/game/baseball-cards-2023-topps-x-bob-ross-the-joy-of/shohei-ohtani-1';return `https://www.sportscardspro.com/search-products?q=${encodeURIComponent(canonicalName(c,{hash:true}))}&type=prices`}
function one30PointUrl(q){return`http://130point.com/api/search/html?${new URLSearchParams({q:q||'',sort:'recent',mp:'all'}).toString()}`}
function marketUrl(k,q,c){const e=encodeURIComponent(q||'');if(k==='ebayActiveRaw')return`https://www.ebay.com/sch/i.html?_nkw=${e}&_sacat=212&LH_PrefLoc=2`;if(k==='ebaySold')return`https://www.ebay.com/sch/i.html?_nkw=${e}&_sacat=212&LH_Sold=1&LH_Complete=1`;if(k==='google')return`https://www.google.com/search?q=${e}`;if(k==='one30point')return one30PointUrl(q);if(k==='sportsCardsPro')return sportsCardsProUrl(c);return'#'}
function idFromPath(){const m=location.pathname.match(/\/cards\/([^/?#]+?)(?:\.html)?\/?$/i);return m?decodeURIComponent(m[1]):null}
function labelIdFromPath(){const queryId=new URLSearchParams(location.search).get('label');if(queryId)return queryId;const m=location.pathname.match(/\/labels\/([^/?#]+?)(?:\.html)?\/?$/i);return m?decodeURIComponent(m[1]):null}
function url(c){return`/cards/${encodeURIComponent(c.id)}.html`}
function labelUrl(c){return`/?label=${encodeURIComponent(c.id)}`}
function qrTarget(c){return c.url||`https://allcardcomps.com/cards/${c.id}.html`}
function qrImg(c){return`https://quickchart.io/qr?text=${encodeURIComponent(qrTarget(c))}&size=220&margin=1&ecLevel=Q`}
function cardById(id){return S.cards.find(c=>String(c.id)===String(id))}
function setKey(c){return`${c.year}||${c.set}`}
function setOptions(){const seen=new Map();S.cards.forEach(c=>{if((!S.year||c.year===S.year)&&c.set)seen.set(setKey(c),c)});return[...seen.values()].sort((a,b)=>(+b.year||0)-(+a.year||0)||collator.compare(a.set,b.set))}
function refreshSetOptions(){const select=document.getElementById('setSel');if(!select)return;const options=setOptions();select.innerHTML=`<option value="">${S.year?`All ${esc(S.year)} sets`:'All years and sets'}</option>${options.map(c=>`<option value="${esc(setKey(c))}">${S.year?esc(c.set):`${esc(c.year)} — ${esc(c.set)}`}</option>`).join('')}`;if(options.some(c=>setKey(c)===S.set))select.value=S.set;else S.set=''}
function searchText(c){const q=queries(c);return[c.id,c.title,c.player,c.year,c.set,c.number,c.normalizedNumber,c.searchQuery,c.team,c.parallel,c.conditionFocus,q.ebayActiveRaw,q.ebaySold,q.google,q.one30point,q.sportsCardsPro].join(' ').toLowerCase()}
function nav(){return`<div class="topbar wrap"><div class="brand"><div class="logo">ACC</div><div>All Card Comps</div></div><div class="navActions"><div class="themeToggle" aria-label="Color theme">${themes.map(t=>`<button type="button" data-theme-btn="${t}" aria-label="${t} theme" aria-pressed="${t===(document.documentElement.dataset.theme||'mint')}"></button>`).join('')}</div><a href="/" data-link>Search</a></div></div>`}
function toast(m){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent=m;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),1500)}
async function copyText(x){try{await navigator.clipboard.writeText(x);toast('Copied')}catch{toast('Copy failed')}}
function methodLabel(m){return m==='dataset-market-estimate'?'Market estimate':m==='unpriced'?'Pending comps':clean(m||'Estimate')}
function rawPricing(c){const p=c.pricing?.raw||{};const low=p.lowDisplay||c.estimatedLowMarketPriceDisplay||'',high=p.highDisplay||c.estimatedHighMarketPriceDisplay||'';return{...p,lowDisplay:low,highDisplay:high,confidence:p.confidence||(low&&high?'Medium':'Low'),method:p.method||(low&&high?'dataset-market-estimate':'unpriced'),explanation:p.explanation||(low&&high?'Estimated Raw Value is an estimate calculated from market-value searches. It is provided for reference only and is not representative of actual market value.':'No market-value estimate is available yet. Guide values are intentionally ignored.')}}
function price(c){const p=rawPricing(c);return p.lowDisplay&&p.highDisplay?`<div class="price"><div><strong>Estimated raw value</strong><span>${esc(p.confidence)} confidence</span></div><b>${esc(p.lowDisplay)} - ${esc(p.highDisplay)}</b></div>`:`<div class="price mutedPrice"><div><strong>Estimated raw value</strong><span>Not priced yet</span></div><b>Pending comps</b></div>`}
function pricingPanel(c){const p=rawPricing(c);const range=p.lowDisplay&&p.highDisplay?`${esc(p.lowDisplay)} - ${esc(p.highDisplay)}`:'Pending comps';return`<section class="pricingPanel"><div><span>Estimated raw value</span><strong>${range}</strong></div><div><span>Confidence</span><strong>${esc(p.confidence)}</strong></div><div><span>Method</span><strong>${esc(methodLabel(p.method))}</strong></div><p>${esc(p.explanation)}</p></section>`}
function badges(c){const b=[];if(c.rookie)b.push('RC');if(c.autograph)b.push('Auto');if(c.memorabilia)b.push('Relic');if(c.serial||(c.printRun&&c.printRun!=='0'))b.push(c.printRun&&c.printRun!=='0'?`/${c.printRun}`:'Serial');if(!b.length)b.push(c.parallel||'Base');return`<div class="badges">${b.map(x=>`<span class="badge">${esc(x)}</span>`).join('')}</div>`}
function apply(){const term=S.q.trim().toLowerCase();S.filtered=S.cards.filter(c=>(!S.year||c.year===S.year)&&(!S.set||setKey(c)===S.set)&&(!S.f.rookie||c.rookie)&&(!S.f.autograph||c.autograph)&&(!S.f.memorabilia||c.memorabilia)&&(!S.f.serial||c.serial||(c.printRun&&c.printRun!=='0'))&&(!term||searchText(c).includes(term)))}
function cardTile(c){const q=queries(c);return`<article class="card"><div class="title">${esc(c.title||q.google)}</div>${badges(c)}${price(c)}<div class="actions"><a class="btn primary" href="${url(c)}" data-link>Open</a><a class="btn outline" target="_blank" rel="noopener" href="${marketUrl('google',q.google,c)}">Google</a><a class="btn outline" target="_blank" rel="noopener" href="${marketUrl('ebayActiveRaw',q.ebayActiveRaw,c)}">eBay: Active</a><a class="btn outline" target="_blank" rel="noopener" href="${marketUrl('ebaySold',q.ebaySold,c)}">eBay: Sold</a><a class="btn outline" target="_blank" rel="noopener" href="${marketUrl('one30point',q.one30point,c)}">130PT</a><a class="btn outline" target="_blank" rel="noopener" href="${marketUrl('sportsCardsPro',q.sportsCardsPro,c)}">SportsCardsPro</a><a class="btn printAction" target="_blank" rel="noopener" href="${labelUrl(c)}">Print label</a></div></article>`}
function rows(){const matchCount=document.getElementById('matchCount'),resultMeta=document.getElementById('resultMeta'),pageInfo=document.getElementById('pageInfo'),prev=document.getElementById('prev'),next=document.getElementById('next'),resultsList=document.getElementById('resultsList');const pages=Math.max(1,Math.ceil(S.filtered.length/S.perPage));if(S.page>pages)S.page=pages;const start=(S.page-1)*S.perPage,rs=S.filtered.slice(start,start+S.perPage);matchCount.textContent=fmt.format(S.filtered.length);resultMeta.textContent=S.filtered.length?`Showing ${fmt.format(start+1)}–${fmt.format(start+rs.length)} of ${fmt.format(S.filtered.length)}`:'No matches';pageInfo.textContent=`Page ${S.page} of ${pages}`;prev.disabled=S.page<=1;next.disabled=S.page>=pages;resultsList.innerHTML=rs.length?rs.map(cardTile).join(''):'<div class="panel">No cards matched.</div>'}
function bindCommonClicks(root=document){root.onclick=e=>{const copy=e.target.closest('[data-copy]');if(copy)copyText(copy.getAttribute('data-copy'))}}
function home(){const years=[...new Set(S.cards.map(c=>c.year).filter(Boolean))].sort((a,b)=>(+b||0)-(+a||0)),stats={rookies:S.cards.filter(c=>c.rookie).length,autographs:S.cards.filter(c=>c.autograph).length,relics:S.cards.filter(c=>c.memorabilia).length,numbered:S.cards.filter(c=>c.serial||(c.printRun&&c.printRun!=='0')).length},filters=[['rookie','Rookie'],['autograph','Autograph'],['memorabilia','Relic'],['serial','Numbered']];app.innerHTML=`${nav()}<div class="wrap"><section class="hero"><h1>Find the card. Feel the chase.</h1><p>Search your collection by year, set, player, card number, and the traits that matter.</p></section><section class="panel stats"><div class="stat"><span>Rookie</span><b>${fmt.format(stats.rookies)}</b></div><div class="stat"><span>Autograph</span><b>${fmt.format(stats.autographs)}</b></div><div class="stat"><span>Relic</span><b>${fmt.format(stats.relics)}</b></div><div class="stat"><span>Numbered</span><b>${fmt.format(stats.numbered)}</b></div></section><section class="panel searchShell"><div class="searchbar"><input id="searchInput" type="text" placeholder="Search cards, players, sets, numbers"><select id="yearSel"><option value="">All years</option>${years.map(y=>`<option value="${esc(y)}">${esc(y)}</option>`).join('')}</select><select id="setSel"><option value="">All years and sets</option></select></div><div class="chips">${filters.map(([k,label])=>`<label class="chip"><input id="${k}" type="checkbox"> ${label}</label>`).join('')}</div></section><section class="toolbar"><div><strong id="matchCount">0</strong> matches · <span id="resultMeta"></span></div><div class="pager"><button id="prev" class="btn outline" type="button">Previous</button><span id="pageInfo"></span><button id="next" class="btn outline" type="button">Next</button></div></section><section id="resultsList" class="results"></section><div class="foot">Verify live sold listings before pricing inventory.</div></div>`;refreshSetOptions();document.getElementById('searchInput').value=S.q;document.getElementById('yearSel').value=S.year;filters.forEach(([k])=>document.getElementById(k).checked=S.f[k]);document.getElementById('searchInput').oninput=e=>{S.q=e.target.value;S.page=1;apply();rows()};document.getElementById('yearSel').onchange=e=>{S.year=e.target.value;S.set='';S.page=1;refreshSetOptions();apply();rows()};document.getElementById('setSel').onchange=e=>{S.set=e.target.value;S.page=1;apply();rows()};filters.forEach(([k])=>document.getElementById(k).onchange=e=>{S.f[k]=e.target.checked;S.page=1;apply();rows()});document.getElementById('prev').onclick=()=>{if(S.page>1){S.page--;rows()}};document.getElementById('next').onclick=()=>{const pages=Math.max(1,Math.ceil(S.filtered.length/S.perPage));if(S.page<pages){S.page++;rows()}};bindCommonClicks(document.getElementById('resultsList'));syncThemeButtons();apply();rows()}
function detail(c){const q=queries(c);const name=esc(c.title||canonicalName(c,{hash:true}));const target=esc(qrTarget(c));const items=[['Google',marketUrl('google',q.google,c)],['eBay: Active',marketUrl('ebayActiveRaw',q.ebayActiveRaw,c)],['eBay: Sold',marketUrl('ebaySold',q.ebaySold,c)],['130PT',marketUrl('one30point',q.one30point,c)],['SportsCardsPro',marketUrl('sportsCardsPro',q.sportsCardsPro,c)]];app.innerHTML=`${nav()}<div class="wrap"><a class="btn outline backLink" href="/" data-link>← Back</a><section class="panel detail"><div class="detailMain"><h2>${esc(c.title||q.google)}</h2>${badges(c)}<div class="metaGrid"><div class="meta"><strong>Player</strong><br>${esc(c.player)}</div><div class="meta"><strong>Year</strong><br>${esc(c.year||'')}</div><div class="meta"><strong>Set</strong><br>${esc(c.set)}</div><div class="meta"><strong>Card #</strong><br>${esc(c.number||'')}</div></div>${pricingPanel(c)}<h3>Marketplace searches</h3><div class="marketGrid">${items.map(([label,href])=>`<div class="market"><strong>${esc(label)}</strong><div class="actions"><a class="btn primary" target="_blank" rel="noopener" href="${href}">Open</a></div></div>`).join('')}</div><div class="labelPanel"><div class="labelPreview"><img src="${qrImg(c)}" alt="QR code"><div class="labelCopy"><div class="labelName">${name}</div><div class="labelUrl">${target}</div></div></div><a class="btn printAction" target="_blank" rel="noopener" href="${labelUrl(c)}">Print label</a></div></div></section></div>`;bindCommonClicks(document)}
function labelPage(c){const name=esc(c.title||canonicalName(c,{hash:true}));const target=esc(qrTarget(c));app.innerHTML=`<main class="labelPage"><div class="labelPreview"><img src="${qrImg(c)}" alt="QR code"><div class="labelCopy"><div class="labelName">${name}</div><div class="labelUrl">${target}</div></div></div><div class="labelControls"><button id="printNow" class="btn primary" type="button" onclick="window.print()">Print</button><button id="closeLabel" class="btn outline" type="button" onclick="window.close()">Close</button></div><p class="printFallback">Print dialog not opening? Press Ctrl+P.</p></main>`}
function router(){const labelId=labelIdFromPath();if(labelId){const c=cardById(labelId);c?labelPage(c):home();return}const id=idFromPath();if(id){const c=cardById(id);c?detail(c):home()}else home()}
document.addEventListener('click',e=>{const theme=e.target.closest('[data-theme-btn]');if(theme){setTheme(theme.dataset.themeBtn);return}const a=e.target.closest('a[data-link]');if(a){e.preventDefault();history.pushState(null,'',a.getAttribute('href'));router()}});addEventListener('popstate',router);fetch('/cards.json',{cache:'no-store'}).then(r=>r.json()).then(d=>{S.cards=d.cards||[];router()}).catch(e=>{app.innerHTML=`${nav()}<div class="wrap"><div class="panel"><h2>Could not load cards.json</h2><p>${esc(e.message)}</p></div></div>`});
